### ISSUE TITLE
Prints a 3 at guidance script startup.

### ISSUE THREAD

**Issue by richarthurs** [Team-Guardian/guardian_guidance#1]
When you start the guidance script, it prints '3' for some reason.

**Comment by darwinchang** [comment]
TL;DR **searchPattern,py line 27 prints out the 3**

Prints a 3 because,
-Running script from guidance2.py at line 50 it calls on **mission.py**
-Line 50 calls on Mission() from mission.py
-In Mission() line 29 calls from _SearchPattern( )_ from **searchPattern.py**
-Line 22-27 you defined _def generate_waypoints( )_
-Line 27 _print self.num_waypoints_, prints out 3. 
_#self.num_waypoints= len(self.waypoints)=3_

**Comment by richarthurs** [comment]
Thanks! Fixed in #b2d300efec542f8ee544520af6321c881a11f9ef
